version: "3"
services:
  app:
    container_name: embedding-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000  # Map container port 8000 to host's PORT
    environment:
      - PORT=8000  # Expose FastAPI on port 8000
      - RERANKER_TYPE=bge-m3  # Model type for reranker
      - DEVICE=cpu  # Device for running the model (e.g., cpu or cuda)
    restart: always  # Restart container if it crashes
    volumes:
      - .:/app